#!/usr/bin/env bash
# install_wifi_permissions.sh
# Installs the polkit rule that allows mempaper's service user to manage
# NetworkManager connections (required for setup hotspot onboarding).
#
# Run once on the Raspberry Pi:
#   sudo bash ~/btc-mempaper/tools/install_wifi_permissions.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RULES_SRC="${SCRIPT_DIR}/90-mempaper-wifi.rules"
RULES_DEST="/etc/polkit-1/rules.d/90-mempaper-wifi.rules"
SERVICE_USER="${1:-pi}"   # pass different user as first argument if needed

if [ "$(id -u)" != "0" ]; then
    echo "❌  This script must be run with sudo."
    echo "    sudo bash $0"
    exit 1
fi

echo "📋 Installing polkit rule for mempaper Wi-Fi onboarding…"
cp "${RULES_SRC}" "${RULES_DEST}"
chmod 644 "${RULES_DEST}"
echo "✅  Rule installed: ${RULES_DEST}"

# --- sudoers: scoped passwordless sudo for all mempaper operations ----------
# settings.modify.system cannot be granted via polkit rules/pkla on
# Raspberry Pi OS Bookworm without polkit-pkla-compat.  A narrow sudoers
# entry is the most reliable approach on embedded Pi OS.
# All rules are restricted to the exact commands mempaper actually runs.
# See docs/SECURITY_GUIDE.md for threat model and rationale.
SUDOERS_FILE="/etc/sudoers.d/mempaper-wifi"
APT_INSTALL_WRAPPER="/usr/local/bin/mempaper-apt-install"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
NMCLI_BIN="$(which nmcli    2>/dev/null || echo /usr/bin/nmcli)"
IW_BIN="$(which iw          2>/dev/null || echo /usr/sbin/iw)"
IPTABLES_BIN="$(which iptables 2>/dev/null || echo /usr/sbin/iptables)"
SYSTEMCTL_BIN="$(which systemctl 2>/dev/null || echo /usr/bin/systemctl)"
DNSMASQ_BIN="$(which dnsmasq 2>/dev/null || echo /usr/sbin/dnsmasq)"
KILL_BIN="$(which kill      2>/dev/null || echo /bin/kill)"
PKILL_BIN="$(which pkill    2>/dev/null || echo /usr/bin/pkill)"
MOUNT_BIN="$(which mount    2>/dev/null || echo /bin/mount)"
APT_GET_BIN="$(which apt-get 2>/dev/null || echo /usr/bin/apt-get)"
APT_BIN="$(which apt       2>/dev/null || echo /usr/bin/apt)"
TEE_BIN="$(which tee        2>/dev/null || echo /usr/bin/tee)"
CAT_BIN="$(which cat        2>/dev/null || echo /bin/cat)"
CHMOD_BIN="$(which chmod    2>/dev/null || echo /bin/chmod)"
MKDIR_BIN="$(which mkdir    2>/dev/null || echo /bin/mkdir)"

# Install apt wrapper script — installs only packages from apt-requirements.txt,
# accepts no arguments so the sudoers rule cannot be exploited to install arbitrary packages.
cat > "${APT_INSTALL_WRAPPER}" <<WRAPPER
#!/bin/bash
APT_REQ="${PROJECT_DIR}/apt-requirements.txt"
if [ ! -f "\$APT_REQ" ]; then
    echo "❌ apt-requirements.txt not found: \$APT_REQ" >&2
    exit 1
fi
PKGS=\$(grep -v '^\s*#' "\$APT_REQ" | grep -v '^\s*\$' | tr '\n' ' ')
if [ -z "\$PKGS" ]; then
    echo "No packages listed in apt-requirements.txt — nothing to install."
    exit 0
fi
exec apt-get install -y --no-upgrade \$PKGS
WRAPPER
chown root:root "${APT_INSTALL_WRAPPER}"
chmod 755 "${APT_INSTALL_WRAPPER}"
echo "✅  apt install wrapper installed: ${APT_INSTALL_WRAPPER}"

# Install Python upgrade wrapper — runs tools/upgrade_python.sh --force --no-restart
# Scoped: no arguments, executes a single known script path, cannot be used arbitrarily.
UPGRADE_PYTHON_WRAPPER="/usr/local/bin/mempaper-upgrade-python"
cat > "${UPGRADE_PYTHON_WRAPPER}" <<WRAPPER
#!/bin/bash
exec bash "${PROJECT_DIR}/tools/upgrade_python.sh" --force --no-restart
WRAPPER
chown root:root "${UPGRADE_PYTHON_WRAPPER}"
chmod 755 "${UPGRADE_PYTHON_WRAPPER}"
echo "✅  Python upgrade wrapper installed: ${UPGRADE_PYTHON_WRAPPER}"

cat > "${SUDOERS_FILE}" <<EOF
# mempaper sudoers rules — generated by tools/install_wifi_permissions.sh
# Rules are scoped to the exact commands mempaper runs. See docs/SECURITY_GUIDE.md.

# WiFi management via NetworkManager.
# nmcli uses many subcommands so kept broad; it does not execute arbitrary code.
${SERVICE_USER} ALL=(root) NOPASSWD: ${NMCLI_BIN}

# Passive WiFi scan during AP mode (read-only — no network changes possible)
${SERVICE_USER} ALL=(root) NOPASSWD: ${IW_BIN} dev * scan passive

# Captive-portal NAT rules: redirect HTTP/HTTPS ports to Flask
${SERVICE_USER} ALL=(root) NOPASSWD: ${IPTABLES_BIN} -t nat -A PREROUTING *
${SERVICE_USER} ALL=(root) NOPASSWD: ${IPTABLES_BIN} -t nat -D PREROUTING *
# Captive-portal filter rules: block DNS-over-TLS leakage from clients
${SERVICE_USER} ALL=(root) NOPASSWD: ${IPTABLES_BIN} -t filter -I FORWARD *
${SERVICE_USER} ALL=(root) NOPASSWD: ${IPTABLES_BIN} -t filter -D FORWARD *

# Captive-portal DNS: dnsmasq on-demand, scoped to known temp paths
${SERVICE_USER} ALL=(root) NOPASSWD: ${DNSMASQ_BIN} --conf-file=/tmp/mempaper-captive-dns.conf --pid-file=/tmp/mempaper-captive-dns.pid

# Stop captive-portal dnsmasq by PID (numeric PID only — no signal flags, blocks kill -9 and kill PID 1)
${SERVICE_USER} ALL=(root) NOPASSWD: ${KILL_BIN} [1-9][0-9]*
# Stop captive-portal dnsmasq by process match (scoped to known config path)
${SERVICE_USER} ALL=(root) NOPASSWD: ${PKILL_BIN} -f /tmp/mempaper-captive-dns.conf

# Remount root filesystem rw/ro around apt operations (read-only Pi OS root partition)
${SERVICE_USER} ALL=(root) NOPASSWD: ${MOUNT_BIN} -o remount\,rw /
${SERVICE_USER} ALL=(root) NOPASSWD: ${MOUNT_BIN} -o remount\,ro /

# System package updates (for SSH admin maintenance via 'ssh mempaper@<ip>')
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_BIN} update
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_BIN} upgrade -y
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_BIN} autoremove -y
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_GET_BIN} update
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_GET_BIN} upgrade -y
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_GET_BIN} autoremove -y

# Scoped apt install wrapper — only installs packages from apt-requirements.txt,
# accepts no arguments (no wildcard, cannot be used to install arbitrary packages).
${SERVICE_USER} ALL=(root) NOPASSWD: ${APT_INSTALL_WRAPPER}

# Python minor-version upgrade wrapper — unholds, upgrades, rebuilds venv.
# Scoped to a single fixed script path; cannot install arbitrary packages.
${SERVICE_USER} ALL=(root) NOPASSWD: ${UPGRADE_PYTHON_WRAPPER}

# Service control
${SERVICE_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL_BIN} restart mempaper.service
${SERVICE_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL_BIN} daemon-reload
${SERVICE_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL_BIN} reboot

# Service file self-update: mempaper can regenerate and install its own unit file.
# tee is scoped to the exact service file path only.
${SERVICE_USER} ALL=(root) NOPASSWD: ${TEE_BIN} /etc/systemd/system/mempaper.service

# SSH key management for pi user (web GUI provisioning of admin SSH access)
${SERVICE_USER} ALL=(root) NOPASSWD: ${MKDIR_BIN} -p /home/pi/.ssh
${SERVICE_USER} ALL=(root) NOPASSWD: ${TEE_BIN} /home/pi/.ssh/authorized_keys
${SERVICE_USER} ALL=(root) NOPASSWD: ${CHMOD_BIN} 700 /home/pi/.ssh
${SERVICE_USER} ALL=(root) NOPASSWD: ${CHMOD_BIN} 600 /home/pi/.ssh/authorized_keys
${SERVICE_USER} ALL=(root) NOPASSWD: ${CAT_BIN} /home/pi/.ssh/authorized_keys
EOF
chmod 440 "${SUDOERS_FILE}"
# Validate the file (visudo -c exits non-zero if syntax is wrong)
if visudo -c -f "${SUDOERS_FILE}" >/dev/null 2>&1; then
    echo "✅  Sudoers rule installed: ${SUDOERS_FILE}"
else
    echo "❌  Sudoers rule invalid — removing to avoid lockout"
    rm -f "${SUDOERS_FILE}"
fi

# Ensure the service user is in the 'netdev' group
if id -nG "${SERVICE_USER}" | grep -qw netdev; then
    echo "✅  User '${SERVICE_USER}' is already in the 'netdev' group"
else
    echo "➕  Adding '${SERVICE_USER}' to the 'netdev' group…"
    usermod -aG netdev "${SERVICE_USER}"
    echo "✅  Done — group change takes effect on next login / reboot"
fi

# Also install a .pkla (legacy localauthority) file for settings.modify.system
# On Raspberry Pi OS the JavaScript rule alone cannot grant this action.
PKLA_DIR="/etc/polkit-1/localauthority/50-local.d"
PKLA_FILE="${PKLA_DIR}/90-mempaper-wifi.pkla"
mkdir -p "${PKLA_DIR}"
cat > "${PKLA_FILE}" <<'EOF'
[mempaper-wifi-modify-system]
Identity=unix-group:netdev
Action=org.freedesktop.NetworkManager.settings.modify.system
ResultAny=yes
ResultInactive=yes
ResultActive=yes

[mempaper-wifi-network-control]
Identity=unix-group:netdev
Action=org.freedesktop.NetworkManager.network-control
ResultAny=yes
ResultInactive=yes
ResultActive=yes

[mempaper-wifi-enable-disable]
Identity=unix-group:netdev
Action=org.freedesktop.NetworkManager.enable-disable-wifi
ResultAny=yes
ResultInactive=yes
ResultActive=yes
EOF
chmod 644 "${PKLA_FILE}"
echo "✅  Legacy pkla rule installed: ${PKLA_FILE}"

# Restart polkit so the new rule is picked up immediately
echo "🔄  Restarting polkit…"
if systemctl restart polkit 2>/dev/null; then
    echo "✅  polkit restarted"
else
    # Some older Pi OS images use a different unit name
    systemctl restart polkitd 2>/dev/null && echo "✅  polkitd restarted" \
        || echo "⚠️  Could not restart polkit — reboot the Pi to apply the rule"
fi

echo ""
if command -v nmcli >/dev/null 2>&1; then
    _PERMS=$(sudo -u "$SERVICE_USER" nmcli general permissions 2>/dev/null || true)
    _MODIFY=$(echo "$_PERMS" | grep -c 'settings\.modify\.system.*\(yes\|ja\)' || true)
    _SHARE=$(echo  "$_PERMS" | grep -c 'wifi\.share\.protected.*\(yes\|ja\)'   || true)
    if [ "$_MODIFY" -ge 1 ] && [ "$_SHARE" -ge 1 ]; then
        echo "✅  Wi-Fi permissions installed and verified."
    else
        echo "✅  Wi-Fi permissions installed."
        echo "⚠️  Permissions not yet active — a reboot may be required for polkit rules to take effect."
    fi
else
    echo "✅  Wi-Fi permissions installed."
fi
echo ""

# --- Captive-portal DNS (dnsmasq) ---------------------------------------------
# Ensure dnsmasq is installed for wildcard DNS during setup hotspot.
if ! command -v dnsmasq >/dev/null 2>&1; then
    echo "📦  Installing dnsmasq for captive-portal DNS..."
    apt-get install -y dnsmasq >/dev/null 2>&1 || true
    # Disable the system dnsmasq service — we only run it on-demand
    systemctl stop dnsmasq 2>/dev/null || true
    systemctl disable dnsmasq 2>/dev/null || true
fi
# Make sure the system dnsmasq service doesn't interfere
if systemctl is-enabled dnsmasq 2>/dev/null | grep -q enabled; then
    systemctl stop dnsmasq 2>/dev/null || true
    systemctl disable dnsmasq 2>/dev/null || true
    echo "✅  System dnsmasq disabled (mempaper runs its own on-demand)"
fi
echo "✅  dnsmasq available for captive-portal DNS"

# --- Integrated mode cleanup -------------------------------------------------
echo "🔧 Enforcing integrated service mode (no separate onboarding service)…"
systemctl stop mempaper-onboarding.service 2>/dev/null || true
systemctl disable mempaper-onboarding.service 2>/dev/null || true
systemctl mask mempaper-onboarding.service 2>/dev/null || true
rm -f /etc/systemd/system/mempaper-onboarding.service
systemctl daemon-reload

if systemctl enable mempaper.service 2>/dev/null; then
    echo "✅  mempaper.service enabled"
else
    echo "⚠️  Could not enable mempaper.service (generate/install it first if missing)"
fi

echo ""
echo "✅  All done. Reboot to verify integrated hotspot onboarding in mempaper.service."
echo "   Monitor:  sudo journalctl -u mempaper.service -f"
